Fix Weight Scrambling in scGPT
helicalAI/helical pull request #98
Opened 2024-09-27 08:56 UTC by mattwoodx

2024-09-28 09:12 UTC, maxiallard commented on examples/notebooks/Cell-Type-Classification-Fine-Tuning.ipynb
<img width="808" alt="image" src="https://github.com/user-attachments/assets/6fbbc33e-0ffe-46a9-89f2-4d650297ca51">
We might want to recheck this one.. looks like we classify everything as one class.

2024-09-28 09:13 UTC, maxiallard requested changes
Let's try to adjust the UCE head to avoid the overfitting

2024-10-02 14:55 UTC, bputzeys approved these changes

2024-10-02 15:03 UTC, maxiallard approved these changes

2024-10-02 15:08 UTC, merged